### ISSUE TITLE
FederatedStore graphIds swapping in ViewValidation error message

### ISSUE THREAD

**Issue by GCHQDev404** [gchq/Gaffer#2784] opened 2022-10-23 18:14 UTC
class: `FederatedOperationChainValidator`
line: ~122

Why is the order of graphIds changing in the error message?
This is found in Test `FederatedStoreTest` line ~1349 with the regex for graph Order. 
`// Code smell this has been added because the exception message changes the order of graphs.`

When found is the issue localised just to this test?
Fix as required.

**Comment by GCHQDeveloper314** [comment] 2022-10-24 07:45
A potential cause is use of a `Set` object somewhere, these don't always have ordering and the order can be changed when processed by `.stream`. Step though debugging can be used to investigate the origin of the swapping.
It would be useful to first confirm if the order of graphIds was checked in previous version of this test.

**Comment by GCHQDev404** [comment] 2022-10-24 09:57
It was checked,
Currently there is a lot of `containsExcatlyAnyOf` which has snuck in which has hidden some of this.

**Comment by GCHQDev404** [comment] 2022-10-24 10:14
Examine branch  [gh-2784-federatedstore-graphids-changing-order ](https://github.com/gchq/Gaffer/tree/2784-federatedstore-graphids-changing-order)

I've added `//TODO FS graphId Order` of location of interst.

UPDATE and edit to this branch.
I think graphID order is maintained WHEN you ask for "graphC,graphD,graphA" you get it in that order.
but getGraphs without specifying ID may just get graphs in ANY order since user provide graphIds.

**Comment by GCHQDev404** [comment] 2022-10-24 10:18
if so remove `// Code smell this has been added because the exception message changes the order of graphs.`

**Comment by t92549** [comment] 2022-11-09 11:48
> I think graphID order is maintained WHEN you ask for graphs with graphID="graphC,graphD,graphA" then you get graphs in that order. BUT when you getGraphs without specifying graphIds it may just get graphs in ANY order since user is not providing graphIds.
> which may be fine. or maybe confusing.

@GCHQDev404 Is this because the underlying data store for the graphs is an unordered cache? What order would you expect them in? Age? Alphabetical? Could always just add sorting

**Comment by GCHQDev404** [comment] 2022-11-15 12:39
as a team we are happy with how it works so remove 
`// Code smell this has been added because the exception message changes the order of graphs.`

**Comment by GCHQDeveloper314** [comment] 2022-11-23 12:22
Was the cause of this determined?

**Comment by t92549** [comment] 2022-11-23 17:58
I think the cache implementation is unordered, and the way the streams work means they will come back in an unreliable order. I presume it always worked like this, or some of the streaming code has changed.
Maybe should double check this was always the case

**Comment by GCHQDev404** [comment] 2022-11-24 09:50
@t92549 the results came back from the internal java Object of Graph Stores. the has gone and all graphs are returned from cache, this is a recent change. which maybe why a couple tests spotted the difference.

**Comment by t92549** [comment] 2022-11-24 13:22
@GCHQDev404 Yes you're right, it used to ordered as it was stored locally but now order cannot be guaranteed as it comes from an external cache

**Comment by t92549** [comment] 2022-11-24 14:14
Closed by https://github.com/gchq/Gaffer/pull/2828

**Closed by t92549** 2022-11-24 14:14 UTC
Labels: federated-store, doc-needed
