### ISSUE TITLE
Upgrade Accumulo version to 1.9.3

### ISSUE THREAD

**Issue by t11947** [gchq/Gaffer#2249] opened 2020-02-20 15:32 UTC
An upgrade of Apache Accumulo is required from the current version (1.8.X) to 1.9.3. This would allow us to take advantage of some of the containerisation features found in 1.9.X without having to make the breaking changes required when upgrading to Accumulo 2.X.X.

Backwards compatibility should be ensured such that anyone still using older versions of Accumulo can still use the new version of Gaffer without having to upgrade their Accumulo installation. 

Info about 1.9.3 here: https://accumulo.apache.org/release/accumulo-1.9.3/

A precursor to #2201 
Related to #2200

**Comment by macenturalxl1** [comment] 2020-03-12 14:23
Hi, I want to deploy 1.9.3 to an AWS environment and can see there's an AWS deploy & integration test script in gaffer-tools that executes a script called _run-gaffer-integration-tests.sh_ - does that test script run the _./store-implementation/accumulo-store_ module test suite only from this repo? - Or does it run other tests I might have missed?

My reason being I want to run (or at best replicate) those same AWS integration tests locally rather than redeploying to an AWS environement everytime I want to test a change - I want to know if it is running any other tests.

I've also seen there's an _./integration-test_ module that I want to run against upgrade changes and can see where AbstractStoreIT is trying to get store.properties from to set up the tests - where can I set store.properties? Does any of the AWS deployment scripts run these tests?

**Comment by t11947** [comment] 2020-03-12 16:04
Hi @macenturalxl1, 
The script _run-gaffer-integration-tests.sh_ calls 
`mvn verify -Pintegration-test -pl store-implementation/accumulo-store --also-make`
which will run all the accumulo store integration tests, i.e. anything that fits the criteria listed in the maven integration-test plugin (notably not the accumulo store unit tests. These use a SingleUseMockAccumuloStore). Included in these integration tests is the AccumuloStoreITs which will run all the AbstractStoreITs using the accumulo store listed in the store.properties file.

The store.properties file is found in _./store-implementation/accumulo-store/src/test/resources/_.
If you wish to run the tests locally to test the upgrade functionality, I would suggest using a MiniAccumuloStore. Details for deploying this can be found here: https://github.com/gchq/gaffer-tools/tree/develop/mini-accumulo-cluster. 

Hopefully I've answered your questions. Please reply if you have any more questions about this issue or need further clarification. Shall I assign this issue to you?

**Comment by macenturalxl1** [comment] 2020-03-13 12:47
Hi yes please I'll claim it - also thank you for providing those steps.

Just an update where I am - I have my MiniAccumuloStore cluster running locally in tools and swapped the original store.properties in _Gaffer/store-implementation/.../resources/_ out with the one my MiniAccumuloStore cluster has generated. So I can point my _./store-implementation/accumulo-store/_ tests to my Zookeeper instance and cluster running locally. 
(*Correct me if I am on the wrong track)

My integration tests are failing so just trying to set them up correctly - I think it is down to one test is using a root User that does not have authorised access to an aggregated table created in the test - and some tests where unexpected Entities and Edges are being asserted against, or none found at all. This is where I'm up to...

**Comment by macenturalxl1** [comment] 2020-03-17 17:03
I'm struggling to run the integration tests locally - here are the steps I've taken:

gaffer-tools: 
1. Ran MiniAccumuloClusterWithShellController.main from the IDE with no args
2. Copied the store.properties generated (this generated a 'root' user)

Gaffer: 
3. Replaced those properties in to _store.properties, store2.properties_ and _accumuloStoreClassicKeys.properties_ in _accumulo-store/src/test/resources/_ 
   - I've put user as 'root' from the props generated in gaffer-tools
   - and SingleUseAccumuloStore as the gaffer.store.class advised by the README
   - see attachments what those props look like

[store.properties.txt](https://github.com/gchq/Gaffer/files/4344628/store.properties.txt)
[store2.properties.txt](https://github.com/gchq/Gaffer/files/4344625/store2.properties.txt)
[accumuloStoreClassicKeys.properties.txt](https://github.com/gchq/Gaffer/files/4344636/accumuloStoreClassicKeys.properties.txt)

The errors I get from the accumulo-store integration tests are bad authorisations for user root for tables: 
AccumuloAggregationIT
> Error BAD_AUTHORIZATIONS for user root on table graphWithNoAggregators(ID:a)
AccumuloStoreClassicKeysITs
> Error BAD_AUTHORIZATIONS for user root on table integrationTestGraph(ID:1l)

- I think the test might be using root as the User from store.properties as default, I tried `createuser user01` from Accumulo shell then swapping it for root in the props so that it matches the test set up but that didn't work
- I got that from the _/create-accumulo-user.sh_ script

Please can you advise on what config I might have missed or how to correct it? Many thanks

**Comment by d47853** [comment] 2020-03-18 14:41
Is it this?: http://apache-accumulo.1065345.n5.nabble.com/Error-BAD-AUTHORIZATIONS-for-user-root-td15152.html

**Comment by phosphorbronze50** [comment] 2020-03-18 15:32
This relates to building gaffer-tools, but it caused by the change of Accumulo version.

Issue:
When gaffer-tools builds I get a compile error with:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile(default-compile) on project performance-testing-aws:Compilation failure[ERROR] /Users/<User Name>/GT2/<Application>-tools/performance-testing/performance-testing-aws/src/main/java/uk/gov/<Department>/<Application>/performancetesting/aws/PublishAccumuloMetricsToCloudWatch.java:[100,57] error: incompatible types: Map<String,String> cannot be converted to SortedMap<String,String>

Explanation:
The AWS CloudWatch reporter gets information from the Accumulo system - a list of tables in the database. This information used to be returned as a SortedMap<String, String> but in the newer version of Accumulo this has been changed to a Map<String, String> (presumably NOT sorting it is more efficient).

Solution:
I have changed the code so the local attribute is now a Map<String, String> and this cures the compilation error. The attribute is private and only used in this immediate area of the code.

Question:
The only impact this will have, I believe, is that when the list of tables is reported in AWS CloudWatch previously the list would have been sorted (alphabetically, presumably); now this order is undefined.
Is this likely to be an issue?
If it is I can put some code in to sort the list of tables.

**Comment by d47853** [comment] 2020-03-18 15:47
Doesn't seem likely to be an issue and it seems like it would be easy to fix in future if it was an issue for someone.

**Comment by t11947** [comment] 2020-03-18 15:54
@phosphorbronze50 Strange, I wonder why this was changed. Looks like this was changed in 1.8.1 > 1.9.0, but I couldn't find anything documenting why. I don't foresee this being an issue.

**Comment by macenturalxl1** [comment] 2020-03-18 16:59
> Is it this?: http://apache-accumulo.1065345.n5.nabble.com/Error-BAD-AUTHORIZATIONS-for-user-root-td15152.html

Thanks, figured it out now - using the shell I've set the scan auths required by the integration tests - this is what I did 
`root@instance> setauths -s vis1,vis2,publicVisibility,privateVisibility,public,private` 

I'll update this in the README too

**Comment by d47853** [comment] 2020-03-30 12:51
Merged into develop

**Closed by d47853** 2020-03-30 12:51 UTC
Labels: dependencies, enhancement, p:high
