### ISSUE TITLE
Check that table was created by Gaffer when initialising AccumuloStore

### ISSUE THREAD

**Issue by gaffer01** [gchq/Gaffer#848] opened 2017-04-25 08:54 UTC
It is surprisingly common for users to think they need to manually create a table in Accumulo before creating an `AccumuloStore`. If they do this then the table will not have the correct Bloom filters and iterators set, and this will cause poor performance and errors.

We should investigate setting a configuration property on a table when Gaffer creates it. Whenever a new store is created against that table, then the property could be checked, and if it is not present then the creation of the store should fail (if there are scenarios where experienced users may need to manually create a table and add iterators, then there could be an option on the store properties to ignore this warning, and carry on, but the default should be to fail).

**Comment by p013570** [comment] 2017-04-26 11:29
This is a duplicate of gh-267. I will add your comment to that issue.

**Closed by p013570** 2017-04-26 11:29 UTC
Labels: enhancement, p:normal
