### ISSUE TITLE
Provide utilities to create standardised schemas for testing purposes

### ISSUE THREAD

**Issue by t616178** [gchq/Gaffer#1656] opened 2018-02-07 11:34 UTC
Add a factory/utility class for creating useful schemas to use within Gaffer's test framework.

This should be done after https://github.com/gchq/Gaffer/issues/1657 and before https://github.com/gchq/Gaffer/issues/1536.

**Comment by m55624** [comment] 2018-10-19 13:31
This is a duplicate of #1833

**Closed by m55624** 2018-10-19 13:31 UTC
Labels: duplicate, enhancement, p:high
