### ISSUE TITLE
Undirected different Vertex edge

### ISSUE THREAD

**Issue by GCHQDeveloper404** [gchq/Gaffer#1782] opened 2018-05-01 11:24 UTC
Links to: gh-1771 

With an unordered edge with different vertex types. src:string dest:int the order doesn't matter, but the types do matter. I experienced a flip in the scr/dest which result in edges failing validation when String vertex fails the IsA(Int) and Int vertex fails IsA(String)

Directed edges do not experience this problem.

**Comment by gaffer01** [comment] 2018-05-01 12:58
For undirected edges, the src and dst are compared (using the compare method if they're comparable, or based on toString if not) and the src set to the first to ensure a consistent representation. This is intentional behaviour.

What is this issue suggesting needs to be done?

**Comment by GCHQDeveloper404** [comment] 2018-05-01 14:45
The solution to problem:
When the Vertex types of an edge are detected to be different, then validate that directed == TRUE, else throws error.

**Comment by p013570** [comment] 2018-05-02 15:00
Merged into develop.

**Comment by gaffer01** [comment] 2018-05-03 08:48
This is a breaking change - anyone with a schema with undirected edges with different types at the end will find that their schema no longer works.

I guess the point is that that didn't work anyway in a store that did serialisation because if the edge got flipped then it wouldn't know which serialiser to use, but the issue doesn't actually say that. And it could have worked if the user had allowed for it in their serialiser, so that does make it a breaking change.

An alternative solution would be to identify the case that where the schema says the edge is undirected but the source and destination types are different and automatically use a serialiser that included the type of the vertex and then delegated to the user's serialiser.

We seem to have limited the schema purely for the convenience of the MultiSerialiser.

**Comment by p013570** [comment] 2018-05-09 06:41
@gaffer01 - sorry just seen your comment. That is a very good point. As this has already been merged in, we may need to back the change out if we don't manage to come up with a fix in the next couple of days.

**Comment by p013570** [comment] 2018-05-09 06:43
It might actually work ok, if we just back this change out. The MultiSerialiser will be able to handle the different vertex types, it shouldn't matter which way around the edge it. It just looks a bit funny in your schema, if you have defined an edge that is Integer to String. Then when you query and get an edge back it is String to Integer.

**Comment by GCHQDeveloper404** [comment] 2018-05-10 11:12
It’s not possible for any user to currently be creating “undirected edges with different vertex types”
This is because within the Edge Builder for an undirected edge natural ordering is applied to the src/dst within **orderVertices()**. The user will receive the following example error messages.

```
Validation errors: 
Filter: uk.gov.gchq.koryphe.impl.predicate.IsA@2638011[type=class java.lang.String] returned false for properties: {SOURCE: <java.lang.Long>1}
Filter: uk.gov.gchq.koryphe.impl.predicate.IsA@6ff29830[type=class java.lang.Long] returned false for properties: {DESTINATION: <java.lang.String>One}
Filter: uk.gov.gchq.koryphe.impl.predicate.IsMoreThan@6a2b953e[controlValue=0,orEqualTo=true] returned false for properties: {DESTINATION: <java.lang.String>One}
```

Change required:
```
private void orderVertices() {
        final boolean edgeWithSameVertexTypes = source.getClass().equals(destination.getClass());
        if (!directed && edgeWithSameVertexTypes) {
            if (VERTEX_COMPARATOR.compare(source, destination) > 0) {
                swapVertices();
            }
        }
    }
```

**Comment by GCHQDeveloper404** [comment] 2018-05-10 11:28
With the change to **orderVertices()** the enforcement of ordering can be undone.

**Comment by gaffer01** [comment] 2018-05-10 14:16
> It’s not possible for any user to currently be creating “undirected edges with different vertex types”

I think it is possible. The following code which creates an undirected edge from a string to an integer works fine:

     Edge e = new Edge.Builder().source("A").dest(1).directed(false).build();

The errors you post are only from a schema that contains validation that the source is a String and the destination is an integer. If the edge is undirected you shouldn't be doing that validation as they may get flipped so that the ordering is consistent.

**Comment by gaffer01** [comment] 2018-05-10 14:53
My original comment on this issue was that there is no issue. It's working as intended. I haven't seen anything above to change that.

The only possible issue is that if you have different vertex types for source and destination in an undirected edge then we may use the wrong serialiser, e.g. if the source is a string and the destination is an integer, then if they're flipped when an edge is created, we may try to use a string serialiser for the integer. There are a few possible solutions:

- Leave it as is and document that if you use different types in undirected edges your serialiser has to deal with that, or else it breaks;
- Not allow schemas with different types for the source and destination in undirected edges (but I'm not sure we can do that - the directed field is just a type and we may not know when that is always false);
- Spot situations where the serialiser for the source and destination in an undirected edge are different and automatically add information to the serialisation that specifies which was used.

**Comment by gaffer01** [comment] 2018-05-10 14:59
In the PR that's been merged for this, what does the line

     if (!srcClazz.equals(dstClazz) && !Boolean.valueOf(edgeDef.getDirected())) 

actually achieve? `edgeDef.getDirected()` returns the name of the type, not the class so testing `Boolean.valueOf(edgeDef.getDirected())` is true doesn't achieve anything.

In the test `shouldValidateEdgeWithDifferentVertexDirectionTrue`, if you change the name of the type from "true" to "myTrue" then it fails and says it's invalid, even though we don't know it's an undirected edge. All we know is that the type of the directed field is called "myTrue" and is a Boolean. It may always be true and the edge may be directed.

**Comment by GCHQDeveloper404** [comment] 2018-05-10 15:08
@gaffer01 
>  Edge e = new Edge.Builder().source("A").dest(1).directed(false).build();
Have you added that edge to a graph, and got no errors?

**Comment by gaffer01** [comment] 2018-05-10 15:45
That's a bug in the automatic validation then. It's a valid edge and it should be possible to add it to a graph. That doesn't change any of the other arguments.

**Comment by GCHQDeveloper404** [comment] 2018-05-10 16:03
> It's not against the schema. If the edge is undirected, then saying in the schema that the source is a string and the destination is an integer is only saying that one of the vertices is a string and one is an integer. There isn't really a source and a destination in an undirected edge. The getSource() and getDestination() methods on an undirected edge are just ways of returning the 2 vertices, there isn't really a source and a destination.

So currently (the recent change) direction was being enforced for different vertex types, this could be removed. But their needs to be a way to pull the undirected first value from accumulo and place it in either of the field that is expecting a String and the second value into the field that is expecting a Int. Otherwise later validation is going to fail.

> We don't need to retain information in the key package about whether an undirected edge has been flipped, as the flipping is irrelevant. The constructor takes care of deciding which one is the source and which is the destination, by comparing them however it can. This is a convenience method so that representations of undirected edges from toString() or as JSON will always be consistent 

> (if we don't ensure they're ordered then undirected edge A-B would appear different to undirected edge B-A when printed using toString() or converted to JSON - this causes problems for downstream systems).

schema= group:1 scr:String dest:String
input (**a**,**b**) creates an undirected edge src:**a** dest:**b** 
input (**b**,**a**) creates an undirected edge src:**a** dest:**b** 
because vertex types are the same.
In accumulo these will aggregate together and be displayed as src:a dest:b 

schema= group:1 scr:String dest:int
input (a,1) creates an undirected edge src:a dest:1
input (1,a) will fail validation and not make it to store because it's not legal with schema group:1
if you created a new group:2 for (1,a) these will not aggregate because group:1 and group:2 are different edges.

**Comment by gaffer01** [comment] 2018-05-10 16:20
> Otherwise later validation is going to fail.

What later validation? There shouldn't be any validation that assumes that the string is the source and the int is the destination in the case of an undirected edge.

> In accumulo these will aggregate together and be displayed as src:a dest:b

They won't necessarily be aggregated together.

> input (1,a) will fail validation and not make it to store because it's not legal 

It is legal. If it's not the validation is wrong.

> So currently (the recent change) direction was being enforced for different vertex types...

As noted above, the recent change (the one merged in the PR for this issue) doesn't enforce that.

**Comment by GCHQDeveloper404** [comment] 2018-05-10 16:43
> In the PR that's been merged for this, what does the line
> 
>  if (!srcClazz.equals(dstClazz) && !Boolean.valueOf(edgeDef.getDirected())) 
> actually achieve? edgeDef.getDirected() returns the name of the type, not the class so testing Boolean.valueOf(edgeDef.getDirected()) is true doesn't achieve anything.
> 
> In the test shouldValidateEdgeWithDifferentVertexDirectionTrue, if you change the name of the type from "true" to "myTrue" then it fails and says it's invalid, even though we don't know it's an undirected edge. All we know is that the type of the directed field is called "myTrue" and is a Boolean. It may always be true and the edge may be directed.

```
.type("myTrue", new Builder()
                        .clazz(Boolean.class)
                        .validateFunctions(new IsTrue(), new Exists())
                        .build())
```

Nicely spotted thank you.

As described above I now believe the method **validateEdgeWithDifferentVertexTypes()** should now be removed to allow undirected edges with different types, and instead make the changes suggested for **orderVertices()**

**Comment by GCHQDeveloper404** [comment] 2018-05-10 16:53
> That's a bug in the automatic validation then. It's a valid edge and it should be possible to add it to a graph. That doesn't change any of the other arguments.

Are you saying that you believe that creating and undirected **Edge(1,"a",group1)** and adding it to a graph with a schema that is expecting undirected **edge(String,Int,group1)** should be legal and the graph should accept it and all validation should pass? 

If so initially I imagine this would require a special behaviour for validation of undirected edges with different vertex types

**Comment by GCHQDeveloper404** [comment] 2018-05-10 17:04
>>Otherwise later validation is going to fail.
>
>What later validation? There shouldn't be any validation that assumes that the string is the source and the int is the destination in the case of an undirected edge.

When vertex type is defined e.g String.class I think a koryphe validation isA(String) is auto added. So when it see's a Int it fails.

>>In accumulo these will aggregate together and be displayed as src:a dest:b
>
>They won't necessarily be aggregated together.

row1 **scr:a dest:b** 
and 
row2 **src:a dest:b** won't be aggregated together?

>>input (1,a) will fail validation and not make it to store because it's not legal
>
>It is legal. If it's not the validation is wrong.

koryphe validation isA(String)  and isA(Int) get auto added for the src/dest based on schema.

>>So currently (the recent change) direction was being enforced for different vertex types...
>
>As noted above, the recent change (the one merged in the PR for this issue) doesn't enforce that.

Yep thats now a bug, the change to enforce directed edge for different vertex types I don't think should be used I think the whole method should be ripped out and instead **orderVertices()** and possibly **KeyPackage** changed.

**Comment by gaffer01** [comment] 2018-05-11 11:42
> Are you saying that you believe that creating and undirected Edge(1,"a",group1) and adding it to a graph with a schema that is expecting undirected edge(String,Int,group1) should be legal and the graph should accept it and all validation should pass?

Yes, undirected edge 1-"A" is equal to undirected edge "A"-1 (that's what undirected means). So they're both valid. We need to change the validation of undirected edges so that both are valid.

> row1 scr:a dest:b
and
row2 src:a dest:b won't be aggregated together?

They're only aggregated if the group specifies aggregation.

> orderVertices() and possibly KeyPackage changed

I don't see any need to change either of these.

**Comment by gaffer01** [comment] 2018-05-11 11:54
Summary:

- We need to reverse the PR that was merged for this - it doesn't achieve what it was intended to.
- There's a bug in the validation for undirected edges. If the schema says that the source is a string and the destination is an integer, then undirected edge "A"-1 is valid and undirected edge 1-"A" is valid.
- If the user specifies the source is a string and the destination is an integer, and they specify different serialisers for those, then there may be issues serialising / deserialising. Options:
  - Leave it as is and document that if you use different types in undirected edges your serialiser has to deal with that, or else it breaks;
  - Not allow schemas with different types for the source and destination in undirected edges (but I'm not sure we can do that - the directed field is just a type and we may not know when that is always false);
   - Spot situations where the serialiser for the source and destination in an undirected edge are different and automatically add information to the serialisation that specifies which was used (but again we can't always tell from the schema whether an edge could be undirected - it could be of type "myBooleanType" which is of class Boolean and not have any validation logic - then we don't know whether it's undirected or not).

**Comment by GCHQDeveloper404** [comment] 2018-05-14 13:36
- Users should be able to specify Undirected Different Vertex Type Edge.
- The Edge Builder for a UDVT edge will behind the scenes order based on the vertex classes.
- The Schema builder for a UDVT edge will also order the schema based on vertex classes.

User defines UDVT edge schema as (src: Z.class, dest: A.class) schema.builder creates (src:A.class, dest:Z.class)
User defines UDVT edge as (z, a) edge.builder creates (a,z)
User defines UDVT edge as (a, z) edge.builder still creates (a,z)
UDVT Schema and UDVT edges alway match up.
MultiSerialiser takes care of the serialisation of these types.

A User should not be confused when schema and edges are returned in a different order to the input as they have already specified that the edge is undirected.

**Comment by GCHQDeveloper404** [comment] 2018-05-14 16:44
PR added to remove the bug.

Currently a Directed Edge with different vertex types work, an undirected Edge does not.

**Comment by gaffer01** [comment] 2018-05-14 16:52
The vertices in the schema cannot be reordered as the schema does not tell us whether an edge is undirected. The schema might tell us this if the user specifies the validation logic but they may not specify any validation logic at all so we will not know whether the edge is undirected (and it's possible to have directed and undirected edges for the same group).

Something to think about for version 2.0: I don't know why the schema accepts a type for the directed field. There are only 3 possibilities: every edge in that group is directed, every edge is undirected, or there is a mixture. It could just be an enum. I'll raise an issue for this.

**Comment by p013570** [comment] 2018-05-15 06:33
Merged into develop.

**Closed by p013570** 2018-05-15 06:33 UTC
Labels: bug, p:normal
