### ISSUE TITLE
Add the ability to give users read only access to federated graphs

### ISSUE THREAD

**Issue by p013570** [gchq/Gaffer#1827] opened 2018-07-09 10:11 UTC
Currently when you add a graph to the federated store you can specify graphAuths. These auths give users full read/write access to the graph. We should add graphWriteAuths to allow the graph to be locked down.

For backwards compatibility, we will need the logic to behave the same as it currently does when graphWriteAuths is set to null.

I.e if graphWriteAuths is null, the all users with access to graphAuths will be given read/write access. If graphWriteAuths is an empty, then users with access to graphAuths are only given read access. If graphWriteAuths contains auths then only users with those auths can write to the graph.

Users without write access should not be allowed to delete the Graph using RemoveGraph operation. They should also not be allow to run specific operations on the graph, such as AddElements. This list of 'add' operations should be configurable by a sys admin via the federated store properties.

**Comment by GCHQDev404** [comment] 2021-04-07 16:18
@m29827 can you confirm if this is a duplicate of gh-2295 and has already been satisfied.

**Comment by n3101** [comment] 2021-04-07 16:41
@p013570 There is a theory, see above, that this issue has been covered by gh-2295. Are you happy that this is the case and therefore for your issue to be closed?

**Comment by n3101** [comment] 2021-08-10 17:32
There is an existing ability to give users read only access to federated graphs using readAccessPredicate, which is being documented in https://github.com/gchq/gaffer-doc/issues/219. This issue does therefore appear to have been duplicated.

**Closed by n3101** 2021-08-10 17:32 UTC
Labels: duplicate, enhancement, p:normal, federated-store
