### ISSUE TITLE
Remove FederatedStore reference from HasTraitsHandler 

### ISSUE THREAD

**Issue by GCHQDev404** [gchq/Gaffer#2812] opened 2022-11-11 13:36 UTC
**Describe the new feature you'd like**
Remove FederatedStore reference from HasTraitsHandler 

**Why do you want this feature?**
package Core shouldn't have references to FederatedStore package. It uses a local String "FederatedStore.processed".

**Comment by GCHQDeveloper314** [comment] 2023-07-03 16:38
The reference is there because it is required by some code which filters out any options with a key matching that string. These options are then used with a `GetTraits` operation to fetch the list of traits to compare against to find if the graph "`HasTrait`". The commit adding this said "Changed HasTraitHandler to not send Federated loop option".

I would guess that this is or was required in a case where the `HasTrait` operation has been processed by a federated store and the `GetTraits` operation is to be sent to a federated store. In this case, if the options are sent as is then it would not be processed because it was marked as already processed by a federated store. This probably relates to loops of federated and/or proxy stores.

It's possible this code is not required anymore due to refactoring of trait handling in the ProxyStore.

I would suggest removing this code and if there are any problems, fixing them in the federated store or proxy store. As stated, it is undesirable for this package to have any references to the federated store.

An inferior solution would be to include only the necessary options when executing `GetTraits`, instead of removing the federated store specific option. This would have the desired effect but without the reference to the federated store.

**Comment by GCHQDeveloper314** [comment] 2023-07-04 09:20
This is a duplicate of #2578

**Closed by GCHQDeveloper314** 2023-07-04 09:20 UTC
Labels: enhancement
